export const LOAD_SUBMISSIONS_SUCCESS = "LOAD_SUBMISSIONS_SUCCESS";
export const ADD_SUBMISSION_SUCCESS = "ADD_SUBMISSION_SUCCESS";
export const CLEAR_SUBMISSIONS = "CLEAR_SUBMISSIONS";

//export const APPEND_DRINKS = "APPEND_DRINKS";
//export const UPDATE_DRINK = "UPDATE_DRINK";

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
