export const LOAD_DRINKS_SUCCESS = "LOAD_DRINKS_SUCCESS";
export const CLEAR_DRINKS = "CLEAR_DRINKS";

export const APPEND_DRINKS = "APPEND_DRINKS";
export const UPDATE_DRINK = "UPDATE_DRINK";

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
