export const LOAD_SUBMISSIONS_SUCCESS = "LOAD_SUBMISSIONS_SUCCESS";
export const ADD_SUBMISSION = "ADD_SUBMISSION";
export const UPDATE_SUBMISSION = "UPDATE_SUBMISSION";
export const DELETE_SUBMISSION = "DELETE_SUBMISSION";

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

export const FETCH_REQUESTED = "FETCH_REQUESTED";
export const FETCH_RECIEVED = "FETCH_RECIEVED";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
